import {
  WORK_TIME_LIST,
  YEAR_ARRAY,
  EDU_DEGREE_ARRAY,
  SERVICE_CATEGORIES,
  FORBIDDEN_WORDS,
} from "./data";

export {
  WORK_TIME_LIST,
  YEAR_ARRAY,
  EDU_DEGREE_ARRAY,
  SERVICE_CATEGORIES,
  FORBIDDEN_WORDS,
};
