import { Dimensions, StyleSheet } from "react-native";
import { COLORS } from "../../../constants/themes/colors";

const screenWidth = Dimensions.get("screen").width;
const styles = StyleSheet.create({
  notFoundTab: {
    width: "100%",
    minHeight: 250,
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  notFoundText: {
    fontFamily: "EinaSemiBold",
    fontSize: 14,
    lineHeight: 20,
    color: COLORS.black500,
  },
  createSection: {
    width: "100%",
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: COLORS.whiteBG,
    borderWidth: 0,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: COLORS.black50,
    gap: 4,
  },
  sectionLabel: {
    fontFamily: "EinaSemiBold",
    fontSize: 16,
    lineHeight: 20,
    color: COLORS.black900,
  },
  sectionBtmText: {
    fontFamily: "EinaRegular",
    fontSize: 14,
    lineHeight: 20,
    color: COLORS.black900,
  },
  sectionBtmErrText: {
    fontFamily: "EinaRegular",
    fontSize: 14,
    lineHeight: 20,
    color: COLORS.redWarning,
  },
  priceChargeTabList: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  priceChargeTabDefault: {
    width: "auto",
    height: 36,
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  priceChargeTabChoosen: {
    backgroundColor: COLORS.blueLight,
    borderWidth: 1,
    borderColor: COLORS.blueNormal,
  },
  priceChargeDefault: {
    fontFamily: "EinaRegular",
    fontSize: 16,
    lineHeight: 24,
    color: COLORS.black900,
    textTransform: "capitalize",
  },
  photoSelectorTouchpad: {
    width: "100%",
    height: 160,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 4,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: COLORS.black100,
    padding: 12,
    gap: 12,
    marginVertical: 8,
  },
  photoSelectorPlaceholder: {
    fontFamily: "EinaSemiBold",
    fontSize: 14,
    lineHeight: 20,
    color: COLORS.black200,
    textAlign: "center",
  },
  photoSelectorInner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  photoSelectorText: {
    fontFamily: "EinaSemiBold",
    fontSize: 14,
    lineHeight: 20,
    color: COLORS.blueNormal,
    textAlign: "center",
  },
  photoPreviewTab: {
    width: 94,
    minWidth: 94,
    height: 60,
    borderRadius: 4,
    backgroundColor: COLORS.gray100,
    position: "relative",
    overflow: "hidden",
  },
  photoPreviewTabClear: {
    width: 24,
    height: 24,
    backgroundColor: COLORS.whiteBG,
    borderRadius: 32,
    borderWidth: 0.3,
    borderColor: COLORS.black50,
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    top: 4,
    right: 4,
    zIndex: 2,
  },
  placeLoadingView: {
    width: "100%",
    height: 100,
    alignItems: "center",
    justifyContent: "center",
  },
  placeListScroll: {
    width: "100%",
    minHeight: 240,
    paddingBottom: 30,
    gap: 4,
  },
  placeTab: {
    width: "100%",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.black50,
    gap: 4,
  },
  placeTextMain: {
    fontFamily: "EinaSemiBold",
    fontSize: 14,
    lineHeight: 20,
    color: COLORS.black500,
    textTransform: "capitalize",
  },
  placeTextSub: {
    fontFamily: "EinaSemiBold",
    fontSize: 14,
    lineHeight: 20,
    color: COLORS.black200,
    textTransform: "capitalize",
  },
  inputBlock: {
    width: "100%",
    gap: 8,
    paddingVertical: 8,
  },
  inputLabel: {
    fontFamily: "EinaSemiBold",
    fontSize: 14,
    lineHeight: 20,
    color: COLORS.black200,
  },
  inputBtmText: {
    fontFamily: "EinaRegular",
    fontSize: 12,
    lineHeight: 20,
  },
  inputTab: {
    width: "100%",
    height: 44,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: COLORS.black100,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 12,
  },
  inputText: {
    fontFamily: "EinaSemiBold",
    fontSize: 16,
    lineHeight: 24,
    color: COLORS.black500,
    width: screenWidth - (24 + 32),
  },
});

export default styles;
